### ISSUE TITLE
gcc/g++ standart

### ISSUE THREAD

**Issue by anarh1st47** [LWSS/Skeletux#1]
Hello,  i've tried build it on gnu compiler collections c++ compiler 5.4 and it looks like it doesnt support inline variables, i've updated g++ to 7 and it works p.

https://github.com/LWSS/Skeletux/blob/master/CMakeLists.txt#L5

I think there should be 7.0 but i didnt found this info on gnu.org, so creating issue, not pull request

PS thanks for this base a lot

**Comment by LWSS** [comment]
yeah I read somewhere that 5.2 they added C++17 but maybe it's called something funky still.

chaged it to 6.0; should be good, i'm on like 8.1.1

**Comment by hashfox** [comment]
I think it was not working on g++6 I may be crazy though didint see this before making my other post
