### ISSUE TITLE
Isses with inline vars [solved with g++8]

### ISSUE THREAD

**Issue by hashfox** [LWSS/Skeletux#4]
I was getting compile time errors such as the bellow:
Skeletux/src/Hooks/../SDK/panorama/PanoramaUIEngine.h:11:31: error: ‘panorama::panelArray’ declared as an ‘inline’ variable
     static inline PanelArray* panelArray;

This is solved with a newer g++ i updated to 8 on debian but installing from unstable

**Comment by anarh1st47** [comment]
which version did u use before?

**Comment by syonfox** [comment]
I think I was using g++-6 before

**Comment by hashfox** [comment]
I think it was g++6
