### ISSUE TITLE
Why panorama insted of sdl/imgui?

### ISSUE THREAD

**Issue by hashfox** [LWSS/Skeletux#5]
I have been working on a similer light version of fuzion using imgui but I might just hijack this and re-add support for imgui/sdl.  Do you think volvo siged imgui? one way to find out I guess.

**Comment by anarh1st47** [comment]
As I know, he's using panorama cuz "another imgui base would be boring"

**Comment by LWSS** [comment]
I had the idea of using the game's built in gui ( like vgui ) for a while. I thought it would be funny to use the game's own UI system.

Panorama came out and I already had the panorama stuff all mapped out for dota, so I ported it over to csgo and it wasn't that hard.

Another nice side effect is that it makes the binary a lot smaller.

However I actually did move it to imgui first, here is a backup at that point in time.
[skeletux_imgui.zip](https://github.com/LWSS/Skeletux/files/2556936/skeletux_imgui.zip)
