### ISSUE TITLE
Crashes CSGO on Injection

### ISSUE THREAD

**Issue by ghost** [LWSS/Skeletux#6]
Ubuntu 18.04.01 compile using "cmake . && make"
CSGO closes after inject, says successfully injected in the loader.
On debug it freezes and doesn't close until gdb abandons CSGO. Compared against Fuzion's initialise routine and can't see any major differences.

Debug output is below:

`➜  Skeletux git:(master) ./debug 
2
Injecting build libskeletux.so
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
---Type <return> to continue, or q <return> to quit---Type "apropos word" to search for commands related to "word".
Attaching to process 28000
[New LWP 28005]
[New LWP 28006]
[New LWP 28007]
[New LWP 28008]
[New LWP 28010]
[New LWP 28035]
[New LWP 28036]
[New LWP 28040]
[New LWP 28041]
[New LWP 28042]
[New LWP 28043]
[New LWP 28045]
[New LWP 28046]
[New LWP 28049]
[New LWP 28050]
[New LWP 28051]
[New LWP 28052]
[New LWP 28055]
[New LWP 28056]
[New LWP 28057]
[New LWP 28058]
[New LWP 28059]
[New LWP 28060]
[New LWP 28061]
[New LWP 28062]
[New LWP 28063]
[New LWP 28065]
[New LWP 28066]
[New LWP 28069]
[New LWP 28070]
[New LWP 28071]
[New LWP 28072]
[New LWP 28073]
[New LWP 28074]
[New LWP 28075]

warning: Could not load shared library symbols for bin/linux64/launcher_client.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007ff7e48949d0 in __GI___nanosleep (requested_time=0x7ffc57605c30, remaining=0x7ffc57605c20) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
28      ../sysdeps/unix/sysv/linux/nanosleep.c: No such file or directory.
(gdb) (gdb) [New Thread 0x7ff7780d2700 (LWP 28111)]
$1 = (void *) 0x38ad2000
(gdb) $2 = (void *) 0x38ad2000
(gdb) 
`

**Comment by postcert** [comment]
Hey, I don't want to drop in and just say "works for me"
But with today's CS:GO revision I have been able to inject and debug w/o issue.

Past debug injection I'm not getting the same "No such file/dir" as you
```
warning: Could not load shared library symbols for bin/linux64/launcher_client.so.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--0x00007f4ab65062d1 in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib/libc.so.6
(gdb) (gdb) c       
Continuing.
```

**Comment by LWSS** [comment]
this project is old and i'm not going to support it :(

check out https://github.com/LWSS/Fuzion instead
